title: Nguyễn Bảo Trung
description: ""
baseurl: ""
url: ""

title-separator: "-"

timezone: "Asia/Bangkok"
markdown: kramdown
mathjax: true
kramdown:
  input: GFM
highlighter: rouge
permalink: /:title

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-katex
  - jekyll-admin
  - jekyll-include-cache
  - jekyll-last-modified-at

sass:
  style: compact

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
